name: Playwright Tests
on:
  pull_request:
    branches: [main, dev]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      # - name: Install server dependencies
      #   run: npm ci
      #   working-directory: ./server
      - name: Install client dependencies
        run: npm ci
      # - name: Install Replay Chromium
      #   run: npx replayio install
      - name: Use CI env
        run: cp .env.test .env.production

      - name: Build Next.js
        run: npm run build
        env:
          SUPABASE_HOSTNAME: ${{ secrets.SUPABASE_HOSTNAME }}
          MOCK_DATA: ${{secrets.MOCK_DATA}}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_HOSTNAME: ${{secrets.SUPABASE_HOSTNAME}}
          SERVER_BASEURL: ${{secrets.SERVER_BASEURL}}
          MOCK_DATA: ${{secrets.MOCK_DATA}}
